//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_assault_night.html
halflife.wad
gfx/env/nightbk.tga
gfx/env/nightdn.tga
gfx/env/nightft.tga
gfx/env/nightlf.tga
gfx/env/nightrt.tga
gfx/env/nightup.tga
cs_assault.wad
maps/zm_assault_night.bsp
