gfx/env/havbk.tga
gfx/env/havdn.tga
gfx/env/havft.tga
gfx/env/havlf.tga
gfx/env/havrt.tga
gfx/env/havup.tga
models/art/2.mdl
models/art/3.mdl
models/radio.mdl
sound/ambience/50s_music.wav
sound/ambience/amb_cavern.wav
sound/ambience/camp_water.wav
sound/ambience/inside_drone.wav
sound/ambience/rumble_loop_3.wav
sound/ambience/steam_release_2.wav
sound/ambience/steamburst1.wav
sound/ambience/steamburst2.wav
sound/ambience/thunder_storm1a.wav
sprites/laserbeam.spr