//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_italy.html
models/player/gsg9/gsg9.mdl
models/player/guerilla/guerilla.mdl
models/zm_italy/doora.mdl
models/zm_italy/entarch1.mdl
models/zm_italy/it_logs.mdl
models/zm_italy/wndc.mdl
models/zm_italy/wndg.mdl
models/zm_italy/wndb.mdl
models/zm_italy/wnda.mdl
models/zm_italy/wndx1.mdl
models/zm_italy/wndc2.mdl
models/zm_italy/doorb.mdl
models/zm_italy/doorc.mdl
models/zm_italy/entarch2.mdl
models/zm_italy/vending_machine.mdl
models/zm_italy/sofa_chair.mdl
models/zm_italy/bookcase_large.mdl
models/zm_italy/mkt_table2.mdl
models/zm_italy/sofa.mdl
models/zm_italy/ladderwood.mdl
models/zm_italy/wndx2.mdl
models/zm_italy/wndz1.mdl
models/zm_italy/cargo.mdl
models/zm_italy/warehouse_shelf001.mdl
models/zm_italy/oildrum001.mdl
sound/zm_italy/zm_italy_amb.wav
zm_italy.wad
maps/zm_italy.bsp
maps/zm_italy.txt
