//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_old_italy_madness.html
halflife.wad
cs_cbble.wad
chateau.wad
maps/zm_old_italy_madness.bsp
